### ISSUE TITLE
Does not work with DropBox

### ISSUE THREAD

**Issue by MarioRicalde** [JumpMaster/PebbleAuth#11]
For some reason this is not working with DropBox.

**Comment by LinkChef** [comment]
My Dropbox 2-Factor token is working as expected and fine.  I have noticed that this can sometimes occur in my own testing, and a simple delete of the token and then re-applying the token seems to work just fine.

If that doesn't work, I'd recommend deleting your Dropbox token, uninstalling, reinstalling, and entering your Dropbox token again, and seeing if the issue still is there.  Then you can describe the issue back here in detail to see if there are any issues that can be fixed.

I've also found an issue with the second font style.  I had no reports of the 2nd font style giving issue to correct Dropbox 2-Factor tokens, but that could very likely be a possibility.

Please note that I'm not the developer, I'm just a user who was testing these things and found a solution out of my own problems.
