### ISSUE TITLE
Web page is incorrect

### ISSUE THREAD

**Issue by fidian** [JumpMaster/PebbleAuth#14]
The Pebble app is taking me to http://oncloudvirtual.com/pebble/pebbleauth/v7/?otp_count=5&theme=0&font_style=1&idle_timeout=60#&ui-state=dialog and that does not match the HTML/JS as provided in the html/ folder.  Is it feasible to update the repository with the new code?

**Comment by JumpMaster** [comment]
Well that's really not too much to ask is it :+1: 

I've added all versions of the configuration page to github.  As of version 2.0 the configuration page will match the version number.  The next release been version 2.0 will have configuration page 20.
